# Generated by Django 5.1.2 on 2025-02-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphabet',
            name='pronunciation_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
